name: Build & push devcontainer

on:
  push:
    branches: main
    paths:
    - 'Dockerfile'
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

concurrency:
    group: main
    cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
        python: ["3.10", "3.11", "3.12"]
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jhginn
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: set tag
        run: |
            echo "TAG=$(echo ${{ matrix.platform }} | tr / -)-ubuntu2204-py$(echo ${{ matrix.python }} | tr -d '.')-$(date +%F | tr -d '-')" >> $GITHUB_ENV
            echo "LATEST_TAG=$(echo ${{ matrix.platform }} | tr / -)-ubuntu2204-py$(echo ${{ matrix.python }} | tr -d '.')-latest" >> $GITHUB_ENV
      - name: Base img
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: jhginn/devcontainer:${{ env.LATEST_TAG }}-base, jhginn/devcontainer:${{ env.TAG }}-base
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
          target: base
      - name: with just
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: jhginn/devcontainer:${{ env.LATEST_TAG }}-just, jhginn/devcontainer:${{ env.TAG }}-just
          build-args: |
              PYTHON_VERSION=${{ matrix.python }}
          target: just
      - name: with terraform
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            platforms: ${{ matrix.platform }}
            push: true
            tags: jhginn/devcontainer:${{ env.LATEST_TAG }}-terraform, jhginn/devcontainer:${{ env.TAG }}-terraform
            build-args: |
                PYTHON_VERSION=${{ matrix.python }}
            target: terraform
      - name: with gcloud
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            platforms: ${{ matrix.platform }}
            push: true
            tags: jhginn/devcontainer:${{ env.LATEST_TAG }}-gcloud, jhginn/devcontainer:${{ env.TAG }}-gcloud
            build-args: |
                PYTHON_VERSION=${{ matrix.python }}
            target: gcloud
