name: Build & push devcontainer

on:
  push:
    branches: main
    paths:
    - 'Dockerfile'
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

concurrency:
    group: main
    cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
        python: ["3.11"]
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jhginn
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: set tag
        run: |
            echo "TAG=${{ matrix.platform }}-p${{ matrix.python }}-$(date +%F | tr -d '-')" >> $GITHUB_ENV
      - name: Base img
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: latest, ${{ env.TAG }}-base
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            POETRY_VERSION=1.8.3
          target: base
      - name: with just
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: latest, ${{ env.TAG }}-just
          build-args: |
              PYTHON_VERSION=${{ matrix.python }}
              POETRY_VERSION=1.8.3
          target: just
      - name: with terraform
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            platforms: ${{ matrix.platform }}
            push: true
            tags: latest, ${{ env.TAG }}-terraform
            build-args: |
                PYTHON_VERSION=${{ matrix.python }}
                POETRY_VERSION=1.8.3
            target: terraform
      - name: with terraform
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            platforms: ${{ matrix.platform }}
            push: true
            tags: latest, ${{ env.TAG }}-gcloud
            build-args: |
                PYTHON_VERSION=${{ matrix.python }}
                POETRY_VERSION=1.8.3
            target: gcloud
